server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.140.211:3306/cskaoyanmall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${filePath}

pagehelper:
  helper-dialect: mysql
logging:
  level:
    com:
      pandax:
        litemall:
          mapper: debug
mybatis:
  type-handlers-package: com.pandax.litemall.handler
filePath: E:\17_th\Spring\myproject\mall\litemall\src\main\resources\static
my:
  visitPath: http://localhost:8081/
  storagePath: E:\17_th\Spring\myproject\mall\litemall\src\main\resources\static\
fileupload:
  secret-id: AKIDKUZWHyXAf1D4mIPBsTzJxXv88wZ0KQLA
  secret-key: leO3Wr4Wr00pFUBj6IKCVjmkZDgx3jJi
  region: ap-shanghai
  bucket: cskaoyanmall-1300668179
  prefix: https://cskaoyanmall-1300668179.cos.ap-shanghai.myqcloud.com/
